from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from .record import Record


class ReviewRepository(Protocol):
    """The human gate. Implementations must allow at most one undecided item per request."""

    def open_review_for(self, request_ref: str) -> Record | None: ...
    def create_review(self, request_ref: str, conversation_id: str, tier: str, summary: str,
                      report: dict) -> str: ...
    def review_packages_excluding(self, request_ref: str) -> Sequence[Record]: ...
    def raise_review_tier(self, review_ref: str, tier: str) -> None: ...
    def review(self, review_ref: str) -> Record | None: ...
    def queue(self) -> Sequence[Record]: ...
    def decide(self, review_ref: str, decision: str, reviewer: str) -> bool: ...
