from __future__ import annotations

from typing import Protocol

from .record import Record


class SessionRepository(Protocol):
    """Which request a conversation is verified for, its attempts, and callback consent."""

    def session(self, conversation_id: str) -> Record | None: ...
    def ensure_session(self, conversation_id: str) -> Record: ...
    def record_attempt(self, conversation_id: str) -> int: ...
    def bind_session(self, conversation_id: str, request_ref: str, provider_id: str) -> None: ...
    def set_callback_consent(self, conversation_id: str) -> None: ...
    def callback_consent(self, conversation_id: str) -> bool: ...
